package comparator

// Comparator compares bodies of unicode text and provides answers.
type Comparator interface {
	// Signature for a given document. Length varies by tuning or implementation.
	Signature(document string) []byte
	// Compare two signatures as generated by the above.
	Compare(sig1, sig2 []byte) (float64, error)
	// Similarity from 0-1, minhash style, on two raw document strings.
	// This is built, of course, from the above two methods. It is assumed to
	// be implemented well enough to prevent errors occurring within Compare, so
	// it should eat or panic on errors instead.
	Similarity(document1, document2 string) float64
	// Same - According to this Comparator's preferences (implementation defined),
	// are these likely the same? e.g. the reference comparator, MinhashComparator,
	// can be set a "Threshold" above which articles are considered the same.
	Same(document1, document2 string) bool
}
